{% set name = "rpthermo" %}
{% set version = "6.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rpThermo/archive/refs/tags/{{ version }}.tar.gz
  sha256: d4b88e6cbde44002f3c212b13fd0c4487f186a4a5ff3792f1e026af9f6ebb08f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - equilibrator-api
    - brs_utils >=1.26.0
    - chemlite
    - rplibs >=6.9.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - rpthermo
  commands:
    - python -m rpthermo --help

about:
  home: https://github.com/brsynth/rpThermo/tree/main
  summary: "Calculate the formation energy of chemical species and the Gibbs free energy for each reaction and for the heterologous pathway itself"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
    - breakthewall
    - tduigou
